<?php

namespace UserBundle\Repository;

/**
 * educationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class educationRepository extends \Doctrine\ORM\EntityRepository
{
}
