user_profil:
    resource: "@UserBundle/Resources/config/routing/profil.yml"
    prefix:   /profil

user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }


redirect_login:
    path: /redirect
    defaults: { _controller: UserBundle:Default:redirect }


account_settings:
    path: /account-settings
    defaults: { _controller: UserBundle:Default:accountSettings }

account_profile:
    path: /profile
    defaults: { _controller: UserBundle:Default:showProfile }