<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTuxczkr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTuxczkr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTuxczkr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTuxczkr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTuxczkr\appDevDebugProjectContainer([
    'container.build_hash' => 'Tuxczkr',
    'container.build_id' => 'fbd3b0a7',
    'container.build_time' => 1575373559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTuxczkr');
