<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfic44i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfic44i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPfic44i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPfic44i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPfic44i\appDevDebugProjectContainer([
    'container.build_hash' => 'Pfic44i',
    'container.build_id' => 'cb56b5c7',
    'container.build_time' => 1575304765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfic44i');
